services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: metastore_db
      MYSQL_USER: hive
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    networks:
      hive-network:
        ipv4_address: 172.20.0.10
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 20

  hive-metastore:
    image: apache_hive_mysql
    container_name: metastore-standalone
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SERVICE_NAME=metastore
      - DB_DRIVER=mysql
      - SERVICE_OPTS=-Djavax.jdo.option.ConnectionDriverName=com.mysql.cj.jdbc.Driver -Djavax.jdo.option.ConnectionURL=jdbc:mysql://172.20.0.10:3306/metastore_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true -Djavax.jdo.option.ConnectionUserName=hive -Djavax.jdo.option.ConnectionPassword=password
    ports:
      - "9083:9083"
    volumes:
      - ./warehouse:/opt/hive/data/warehouse
    restart: unless-stopped
    networks:
      hive-network:
        ipv4_address: 172.20.0.20

  hive-server:
    image: apache_hive_mysql
    container_name: hiveserver2-standalone
    depends_on:
      - hive-metastore
    environment:
      - SERVICE_NAME=hiveserver2
      - SERVICE_OPTS=-Dhive.metastore.uris=thrift://172.20.0.20:9083
      - IS_RESUME=true
    ports:
      - "10000:10000"
      - "10002:10002"
    volumes:
      - ./warehouse:/opt/hive/data/warehouse
    restart: unless-stopped
    networks:
      hive-network:
        ipv4_address: 172.20.0.30

networks:
  hive-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
