networks:
  rabbitmq_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.41.0.0/16
        
        
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
      - TZ=America/Sao_Paulo
    volumes:
      - ./mongo-data:/data/db
    networks:
      rabbitmq_net:
        ipv4_address: 172.41.0.14
        
        
volumes:
  mongo-data:      
