services:
  hive5:
    image: apache/hive:4.0.1
    container_name: hive4
    environment:
      - SERVICE_NAME=hiveserver2
    ports:
      - "10000:10000"
      - "10002:10002"
    networks:
      custom_net:
        ipv4_address: 172.28.0.10
    restart: unless-stopped

networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16